# Generated by Django 4.0.1 on 2022-01-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense', models.CharField(max_length=60, verbose_name='Offense')),
                ('license_number', models.CharField(max_length=10, verbose_name='plates')),
                ('Details', models.TextField(max_length=2048, verbose_name='Details')),
                ('timeenter', models.DateTimeField(verbose_name='timeenter')),
            ],
        ),
        migrations.CreateModel(
            name='Reps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=60, verbose_name='exercisetype')),
                ('reps', models.IntegerField()),
                ('more', models.CharField(max_length=200, verbose_name='morenotes')),
                ('timeenter', models.DateTimeField(verbose_name='timeenter')),
            ],
        ),
        migrations.CreateModel(
            name='Running',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200, verbose_name='notes')),
                ('minutes', models.IntegerField()),
                ('timeenter', models.DateTimeField(verbose_name='timeenter')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200, verbose_name='notes')),
                ('damage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('timeenter', models.DateTimeField(verbose_name='timeenter')),
            ],
        ),
    ]
