# Generated by Django 4.0.1 on 2022-02-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thoughts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('author', models.CharField(max_length=30, verbose_name='Author')),
                ('details', models.TextField(max_length=2048, verbose_name='Details')),
                ('timeenter', models.DateTimeField(verbose_name='TimeEnter')),
            ],
        ),
    ]
